config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
   resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do 
    resource :favorites, only: [:create, :destroy]
   end
   resources :users, only: [:show, :edit, :update, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   get 'ranks/rank' => 'ranks#rank'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   belongs_to :user
   has_many :favorites, dependent: :destroy
   def favorited_by?(user)
    favorites.exists?(user_id: user.id)
   end
    validates :title, presence: true
    validates :body, presence: true, length: {maximum:200}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :books, dependent: :destroy
         has_many :favorites, dependent: :destroy
         validates :name, length: {in: 2..20}, uniqueness: true
         validates :introduction,  length: {maximum:50}

         has_one_attached :profile_image

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no-image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!, except: [:top, :about]
 before_action :configure_permitted_parameters, if: :devise_controller?
 
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :is_matching_login_user, only: [:edit, :update]
  def new
    @book = Book.new
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user

  end

  def show
    @book = Book.find(params[:id])
    @books = @book.user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
    render :index
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
   if @book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book)
   else
    render :edit
   end
  end



   private

  def book_params
    params.require(:book).permit(:title, :body)
  end

   def is_matching_login_user
    book = Book.find(params[:id])
    user_id = book.user.id
    login_user_id = current_user.id
    if(user_id != login_user_id)
      redirect_to books_path
    end
   end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    
    def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to books_path
    end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to books_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
    def rank
  # 投稿のいいね数ランキング
    @book_like_ranks = Post.find(Favorite.group(:book_id).order('count(book_id) desc').pluck(:book_id))
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :is_matching_login_user, only: [:edit, :update]
  def index
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end



  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user)
    else
    render :edit
    end
  end



  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
   def is_matching_login_user
    user_id = params[:id].to_i
    login_user_id = current_user.id
    if(user_id != login_user_id)
      redirect_to user_path(current_user.id)
    end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2 class="mt-3">New book</h2>
  <%= form_with model: book do |f| %>
    <div class="field mb-3">
          <div><%= f.label :title %></div>
          <div><%= f.text_field :title, class:"form-control" %></div>
        </div>

        <div class="field mb-3">
         <div><%= f.label :body %></div>
         <div><%= f.text_area :body, class:"form-control" %></div>
        </div>
        <div>
          <%= f.submit 'Create Book', class:"btn btn-success" %>
        </div>
        <% end %>

app/views/books/edit.html.erb
<body>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>Editing Book</h2>
        <% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
        <%= form_with model: @book do |f| %>
        <div class="form-group">
          <div><%= f.label :title %></div>
          <div><%= f.text_field :title %></div>
        </div>
        <div class="form-group">
          <div><%= f.label :opinion %></div>
          <div><%= f.text_area :body %></div>
        </div>
        <%= f.submit "Update Book", class:"btn btn-success" %>
        <% end %>
        <%= link_to 'Show', book_path %>|<%= link_to 'Back', books_path %>
       
        
      
    
        </div>
    </div>
  </div>
</body>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <div class="row">
    <div class="col-md-3">
      <%= link_to 'a', ranks_rank_path %>
      <h2>User info</h2>

      <%= image_tag @user.get_profile_image(100,100) %>
      <table class="table">
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>

        </tr>
      </table>
      <div class="row">
      <%= link_to edit_user_path(@user), class:"btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
      <% end %>
      </div>
      <%= render 'list', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th cplspan="3"></th>
          </tr>
        </thead>
        <% @books.each do |book| %>
        <tbody>
          <tr>
            <td><%= link_to user_path(book.user_id) do %>
                <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %>
            </td>

            <td><%= link_to book_path(book.id) do %>
                <%= book.title %>
                <% end %>
            </td>
            <td><%= book.body %></td>
            <td><% if book.favorited_by?(current_user) %>
<%= link_to  book_favorites_path(book), method: :delete do %>
  <i class="fas fa-heart"></i>
  <%= book.favorites.count %>
<% end %>
<% else %>
<%= link_to book_favorites_path(book), method: :post do %>
  <i class="far fa-heart"></i>
  <%= book.favorites.count %>
<% end %>
<% end %></td>
            <% end %>


          </tr>
        </tbody>
      </table>


    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>投稿フォーム</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <%= form_with model: @book do |f| %>
    
      
    <h4>title</h4>
      <%= f.text_field :title %>
    <h4>body</h4>
      <%= f.text_area :body %>
    <%= f.submit '投稿' %>
  <% end %>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @book.user.get_profile_image(100,100) %>
      <table class="table">
        <tr>
          <th>name</th>
          <th><%= @book.user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @book.user.introduction %></th>
        </tr>
      </table>
      <div class="row">
      <%= link_to edit_user_path(@books.id), class:"btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
      <% end %>
      </div>
      <%= render 'list', book: Book.new %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td><%= link_to user_path(current_user.id) do %>
                <%= image_tag @book.user.get_profile_image(100,100) %>
                <% end %><br>
                <%= link_to user_path(@book.user.id) do %>
                <%= @book.user.name %>
                <% end %>

            </td>
            <td><%= link_to book_path(@book.id) do %>
                <%= @book.title %>
                <% end %>
            </td>
            <td><%= @book.body %></td>
            <td>
              <% if @book.user == current_user %>
              <%= link_to "Edit", edit_book_path(@book), class: "btn btn-success btn-sm" %>
              <% end %>
            </td>
            <td>
              <% if @book.user == current_user %>
              <%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-danger btn-sm" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
    <div class="row">
      <div class="px-3 mx-auto" >
        <h1>Welcom to <i class="fas fa-book"></i><strong>Bookers !</strong></h1>
      </div>
    </div>
</div>

app/views/homes/top.html.erb
<div>
  <%= flash[:notice] %>
</div>
<div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6" >
        <h1>welcom to <i class="fas fa-book"></i><strong>Bookers !!</strong></h1>
        <p>In <i class="fas fa-book"></i><strong>Bookers,</strong></p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class="mx-auto col-10">
          <%= link_to 'Log in',  new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
          <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-success btn-sm btn-block mb-3 sign_up" %>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2b</title>
    <meta name="viewport" content="width=device-width,initial-scale=1 maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body class="d-flex flex-column vh-100">
     
    <header class="bg-dark">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><span class="text-light">Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            
            <li>
              <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i>Home
              <% end %>
            </li>
            <li>
              <%= link_to users_path, class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i>Users
              <% end %>
            </li>
            <li>
              <%= link_to books_path, class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i>Books
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i>Log out
              <% end %>
             
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i>Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i>About
              <% end %>
              
            </li>
            <li>
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i>Sign up
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i>Log in
              <% end %>
              
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
  <%= yield %>
  <footer>
    <div class="contaimer mt-5">
      <div class="row">
        <div class="mx-auto">
          <P>CopyRight Infratop.inc</P>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/ranks/rank.html.erb
<!--配列の1つ目から順に1位、２位と表示される-->
<% book_ranks.each.with_index(1) do |book, i| %>
  第<%= i %>位
:
<!--表示したいカラムをご自由に-->
:
<% end %>

app/views/users/_list.html.erb
<h2>User info</h2>
      <% books.each do |book| %>
      <%= image_tag book.user.get_profile_image(100,100) %>
      <table class="table">
        <tr>
          <th>name</th>
          <th><%= book.user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th>introduction</th>
          <% end %>
        </tr>
      </table>

app/views/users/edit.html.erb
<body>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
        
        <%= form_with model: @user do |f| %>
        <div class="form-group">
          <div><%= f.label :name %></div>
          <div><%= f.text_field :name %></div>
        </div>
        <div class="form-group">
          <div><%= f.label :image %></div>
          <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
        </div>
        <div class="form-group">
          <div><%= f.label :Introduction %></div>
          <div><%= f.text_area :introduction %></div>
        </div>
        <%= f.submit "Update User", class:"btn btn-secondary" %>
        <% end %>
      </div>
    </div>
  </div>
</body>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>

     <%= image_tag @user.get_profile_image(100,100) %>
     <table class="table">
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>

        </tr>
      </table>
      <div class="row">
      <%= link_to edit_user_path(@user), class:"btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
      <% end %>
      </div>
      <h2 class="mt-3">New book</h2>


      <%= form_with model: @book do |f| %>
      <div class="field mb-3">
        <div><%= f.label :title %></div>
        <div><%= f.text_field :title, class:"form-control" %></div>
      </div>

      <div class="field mb-3">
        <div><%= f.label :body %></div>
        <div><%= f.text_area :body, class:"form-control" %></div>
      </div>
      <div>
         <%= f.submit 'Create Book', class:"btn btn-success btn-sm" %>
      </div>
         <% end %>
    </div>


    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th cplspan="3"></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td><%= image_tag user.get_profile_image(100,100) %></td>
            <td><%= user.name %></td>
            <td><%= link_to 'Show', user_path(user.id) %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>

      <%= image_tag @user.get_profile_image(100,100) %>
      <table class="table">
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      </table>
      <div class="row">
      <%= link_to edit_user_path(@user.id), class:"btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
      <% end %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book do |f| %>
      <div class="field mb-3">
        <div><%= f.label :title %></div>
        <div><%= f.text_field :title, class:"form-control" %></div>
      </div>

      <div class="field mb-3">
        <div><%= f.label :body %></div>
        <div><%= f.text_area :body, class:"form-control" %></div>
      </div>
      <div>
         <%= f.submit 'Create Book', class:"btn btn-success" %>
      </div>
         <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th cplspan="3"></th>
          </tr>
        </thead>
        <% @books.each do |book| %>
         <tbody>
          <tr>
            <td><%= link_to user_path(@user.id) do %>
                <%= image_tag @user.get_profile_image(100,100) %>
                <% end %>
            </td>
            <td> <%= link_to book_path(book.id) do %>
                 <%= book.title %>
                 <% end %>
            </td>
            <td><%= book.body %></td>
            <% end %>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>